add debugger
kmagiera/babel-watch pull request #23
Opened 2016-09-20 19:07 UTC by SupremeTechnopriest

This is the start of adding debugger support to `babel-watch`. We should probably add more options in the future.

## Usage
`babel-watch app.js --debug 5858`

This will start a debugger running on the specified port only on the child process. Im using vscode for my debugging and it works great for me. 

Should allow #18 to move forward.  I know it doesnt support all the debugger options, but its enough for me. 😸

2016-09-21 18:34 UTC, bolinfest commented on babel-watch.js
>  program.option('-o, --only [globs]', 'Matching files will be transpiled');
Should this be `-d`?

2016-09-21 18:35 UTC, SupremeTechnopriest commented
indeed.  good catch.

2016-09-21 18:36 UTC, SupremeTechnopriest commented on babel-watch.js
>  program.option('-o, --only [globs]', 'Matching files will be transpiled');
indeed good catch

2016-09-21 18:37 UTC, bolinfest commented on babel-watch.js
> +  if(program.debug) {
Given the prevailing style in this file, I think you need a space after this `if`.

2016-09-21 18:39 UTC, bolinfest commented on babel-watch.js
> +      process.execArgv.push('--debug=' + (program.debug));
Isn't `restartApp()` called repeatedly? This doesn't seem idempotent. Would it be more appropriate to update the existing line to:

```
const app = fork(path.resolve(__dirname, 'runner.js'), {execArgv: process.execArgv.concat('--debug=' + program.debug) });
```

or something like that?

2016-09-22 20:43 UTC, kmagiera requested changes
Thanks @bolinfest for your suggestions. I agree with all of them. @SupremeTechnopriest would you be able to address these comments?

2016-09-23 04:43 UTC, SupremeTechnopriest commented
Ill make the changes tomorrow (I'm on EST)

2016-09-23 18:00 UTC, SupremeTechnopriest commented
Before I go ahead and fix this, how do you feel about removing the conditional all together and going with something like this:

```javascript
const app = fork( path.resolve(__dirname, 'runner.js'), { 
    execArgv: program.debug ? process.execArgv.concat('--debug=' + program.debug) : process.execArgv 
});
```

2016-09-26 08:47 UTC, kmagiera commented
@SupremeTechnopriest style-wise I'd actually prefer the following construct (not going to be pushing people to write code the same way I do, just saying what my preference is as you're asking):
```
const runnerExecArgv = process.execArgv.slice();
if (program.debug) {
  runnerExecArgv.push('--debug=' + program.debug);
}
const app = fork(path.resolve(__dirname, 'runner.js'), { execArgv: runnerExecArgv });
```

So I'd keep the coditional, as it makes it cleaner that something is happening with the args when you send 'debug' flag to the program, I also create a helper variable "runnerExecArgv" that then is modified in the `if` block. Inlining everything makes the code shorter but not necessarily more readable (e.g. it's been always confusing to me how array methods in JS sometimes mutate the array and sometimes creates a copy, your construct is ok, because concat create a copy, otherwise it might have a side effect, so if I didn't know the js array methods well I'd be confused if you may be using it for the side effect or not; therefore I think my version is easier to understand even if you don't know JS well)

2016-09-26 17:09 UTC, SupremeTechnopriest commented
Okay that latest commit should be in the style you prefer.

2016-09-26 18:06 UTC, kmagiera approved these changes
Sweet, thank you!

2016-09-26 18:06 UTC, merged

2016-09-27 23:09 UTC, bolinfest commented
I'm currently on `2.0.3-rc0`, so is there ultimately supposed to be a `2.0.3` that includes this?